<?php

session_start();
if(!$_SESSION['password'])
{
    header('Location: adminlogin.phtml');
}

$pdo = new PDO('mysql:host=localhost;dbname=blog;port=3306', 'root', 'root');
$pdo->exec('SET NAMES UTF8');
$Id_article = $_GET['Id_article'];


$query = $pdo->prepare
(
    "SELECT * from article WHERE Id_article = ? "
);

$query->execute(array($Id_article));
$Article = $query->fetch();


include('nav_gray.html');
?>
		<main> 
<div class="container">
    <h2 class="text-center">Edit an Article</h2>
	<div class="row justify-content-center">
		<div class="col-12 col-md-8 col-lg-6 pb-5">
        <form method="POST" action="valid_article_modifier.php" >
                        <div class="card border-primary rounded-0">
                            <div class="card-header p-0">
                                <div class="bg-info text-white text-center py-2">
                                    <h3><i class="fas fa-pen"></i> Edit Article</h3>
                                </div>
                            </div>
                            <div class="card-body p-3">

                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fas fa-heading text-info"></i></i></div>
                                        </div>
                                        <input type="text" class="form-control" name="Titre"  value="<?=$Article['Titre']?>">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-user text-info"></i></div>
                                        </div>
                                        <input type="text" class="form-control" name="Auteur"  value="<?=$Article['Auteur']?>">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fas fa-pen text-info"></i></div>
                                        </div>
                                        <textarea type="text" class="form-control" name="Article"  ><?=$Article['Article']?></textarea>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fas fa-dumbbell text-info"></i></i></div>
                                        </div>
                                        <input type="text" class="form-control" name="Categorie"  value="<?=$Article['Categorie']?>">
                                    </div>
                                </div>

                                <input type="hidden" name="Id_article" value="<?=$Id_article?>" />


                                <div class="text-center">
                                    <input type="submit" value="Enregistrer" class="btn btn-info btn-block rounded-0 py-2">
                                </div>
                            </div>
                    </form>
        </div>
	</div>
</div>
        </main>
</body>
</html>