<?php


$pdo = new PDO('mysql:host=localhost;dbname=blog;port=3306', 'root', 'root');
$pdo->exec('SET NAMES UTF8');
$Id_article = $_GET['Id_article'];

$query = $pdo->prepare
(
    "SELECT * from article WHERE Id_article = ?"
);

$query->execute([$_GET['Id_article']]);
$article = $query->fetch();

/*****************************************************************************************************/

$querycomm = $pdo->prepare
            (
                "SELECT * from commentaires WHERE Id_article = ? ORDER BY Date_publication DESC"
            );
            

        $querycomm->execute([$_GET['Id_article']]);

        $commentaires = $querycomm->fetchAll();


if(isset($_POST['Commentpost']))
    {
        if (!empty($_POST['Pseudo']) and !empty($_POST['Commentaire']))
        {

        $inserercomm = $pdo->prepare
        (
            "INSERT INTO commentaires ( Id_article, Pseudo, Commentaire, Date_publication) values ( ?, ?, ?, now())"

        );
        $pseudo_saisi = htmlspecialchars($_POST['Pseudo']);
        $comm_saisi = htmlspecialchars($_POST['Commentaire']);

        $inserercomm -> execute(array($_GET['Id_article'],$pseudo_saisi, $comm_saisi));

        header('Refresh: 0');
        }
        else
        {
            echo "Tous les champs ne sont pas complétés";
        }
    }
    include('nav_gray.html');
?>
        <main> 
        
        
            <?php
                
                echo '<div style="text-align:center; margin:20px">
                <h3> '.$article['Titre'].'</h3></br>
                <p>'.$article['Article'].'</p>
                <p>Rédigé par '.$article['Auteur'].' le '.$article['Date_creation'].'</p>
                </div>
                <hr>';
                foreach($commentaires as $comm)
                    {
                        echo 
                        '<h3>Rédigé par '.$comm['Pseudo'].'</h3>
                        <p>'.$comm['Commentaire'].'</p>
                        <hr>';
                    }
            ?>

<div class="container">
	<div class="row justify-content-center">
		<div class="col-12 col-md-8 col-lg-6 pb-5">
                    <form method="POST" action="" >
                        <div class="card border-primary rounded-0">
                            <div class="card-header p-0">
                                <div class="bg-info text-white text-center py-2">
                                    <h3><i class="fas fa-comments"></i> Write a comment</h3>
                                </div>
                            </div>
                            <div class="card-body p-3">

                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fas fa-heading text-info"></i></i></div>
                                        </div>
                                        <input type="text" class="form-control" name="Pseudo" placeholder="Pseudo">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fas fa-pen text-info"></i></div>
                                        </div>
                                        <textarea type="text" class="form-control" placeholder="Commentaire" name="Commentaire"></textarea>
                                    </div>
                                </div>

                                <input type="hidden" name="Id_article" value="<?=$Id_article?>"/></br>

                                <div class="text-center">
                                    <input type="submit" name="Commentpost" value="Publier" class="btn btn-info btn-block rounded-0 py-2">
                                </div>
                            </div>
                    </form>
                </div>
	</div>
</div>
        </main>
<?php
        include('footer.html');
?>
</body>
</html>