<?php
session_start();
if(!$_SESSION['password'])
{
    header('Location: adminlogin.phtml');
}

$pdo = new PDO('mysql:host=localhost;dbname=blog;port=3306', 'root', 'root');

if(isset($_POST['envoyer']))
{
    if (!empty($_POST['Titre']) and !empty($_POST['Article']) and !empty($_POST['Auteur']) and !empty($_POST['Categorie']))
    {
        
        $insererArticle = $pdo->prepare
        (
            "INSERT INTO article (Titre, Article, Categorie, Auteur, Date_creation) values (?, ?, ?, ? ,now())"
        );

        $titre = htmlspecialchars($_POST['Titre']);
        $article = nl2br(htmlspecialchars($_POST['Article']));
        $categorie = htmlspecialchars($_POST['Categorie']);
        $auteur = htmlspecialchars($_POST['Auteur']);
        

        $insererArticle -> execute(array($titre, $article, $categorie, $auteur ));

        header('Location: administration.phtml');

    }
    else
    {
        $message = "Veuillez compléter tous les champs";
        echo "<script type='text/javascript'>alert('$message');</script>";
    }
}
    include('nav_gray.html');
?>
<main>  

<div class="container">
    <h2 class="text-center">Create an Article</h2>
	<div class="row justify-content-center">
		<div class="col-12 col-md-8 col-lg-6 pb-5">
                    <form method="POST" action="" >
                        <div class="card border-primary rounded-0">
                            <div class="card-header p-0">
                                <div class="bg-info text-white text-center py-2">
                                    <h3><i class="fas fa-newspaper"></i></i> New Article</h3>
                                </div>
                            </div>
                            <div class="card-body p-3">

                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fas fa-heading text-info"></i></i></div>
                                        </div>
                                        <input type="text" class="form-control" name="Titre" placeholder="Titre">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-user text-info"></i></div>
                                        </div>
                                        <input type="text" class="form-control" name="Auteur" placeholder="Auteur">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fas fa-pen text-info"></i></div>
                                        </div>
                                        <textarea type="text" class="form-control" placeholder="Rédaction de l'article" name="Article"></textarea>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="input-group mb-2">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fas fa-dumbbell text-info"></i></i></div>
                                        </div>
                                        <input type="text" class="form-control" name="Categorie" placeholder="Categorie">
                                    </div>
                                </div>


                                <div class="text-center">
                                    <input type="submit" name="envoyer" value="Enregistrer" class="btn btn-info btn-block rounded-0 py-2">
                                </div>
                            </div>
                    </form>
                </div>
	</div>
</div>
    </main>
</body>
</html>
